---
- name: ensure oh-my-zsh repo exists
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh

- name: ensure zshrc is linked
  file: src=~/Dropbox/sync/zsh/.zshrc dest=~/.zshrc state=link
