---
- name: ensure vim is installed with python3 and lua
  homebrew: >
    name=vim
    update_homebrew=yes
    state=latest
    install_options=with-python3,with-lua

- name: ensure vim dotfiles are deployed
  file: src=~/Dropbox/sync/vim/{{ item }} dest=~/{{ item }} state=link
  with_items:
    - .vim
    - .vimrc
